[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"
monitor = "xtask monitor-rust-source"
build-native = "xtask build-native"
build-windows-debug = "build-native --targets windows-x64 android-arm64 --reload-dotnet"
build-windows-release = "build-native --targets windows-x64 android-arm64 --reload-dotnet --release"


[target.aarch64-linux-android]
linker = "clang.exe"

rustflags = [
  "-C", "link-arg=--target=aarch64-linux-android21",
]
